// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ddac.Models;

namespace ddac.Migrations
{
    [DbContext(typeof(ddacContext))]
    partial class ddacContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ddac.Models.Activity", b =>
                {
                    b.Property<int>("Actid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AQty");

                    b.Property<string>("ActName");

                    b.Property<decimal>("ActPrice");

                    b.HasKey("Actid");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("ddac.Models.BeautynSpa", b =>
                {
                    b.Property<int>("Bid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BQty");

                    b.Property<string>("BeautyName");

                    b.Property<decimal>("BeautyPrice");

                    b.HasKey("Bid");

                    b.ToTable("BeautynSpa");
                });

            modelBuilder.Entity("ddac.Models.Hotel", b =>
                {
                    b.Property<int>("Hid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HDateCheckInDate");

                    b.Property<DateTime>("HDateCheckOutDate");

                    b.Property<int>("HQty");

                    b.Property<string>("HotelName");

                    b.Property<decimal>("HotelPrice");

                    b.HasKey("Hid");

                    b.ToTable("Hotel");
                });

            modelBuilder.Entity("ddac.Models.Restaurant", b =>
                {
                    b.Property<int>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("RDateCheckInDate");

                    b.Property<DateTime>("RDateCheckOutDate");

                    b.Property<int>("RQty");

                    b.Property<string>("RestName");

                    b.Property<decimal>("RestPrice");

                    b.HasKey("Rid");

                    b.ToTable("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
